#
# Copyright 2026 Rafał Wabik - IceG - From eko.one.pl forum
#
# Licensed to the GNU General Public License v3.0.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-exigo-hub-d50-5g
PKG_MAINTAINER:=Rafał Wabik <4Rafal@gmail.com>
LUCI_TITLE:=LuCI JS support for Xunison Exigo Hub D50 5G
LUCI_DESCRIPTION:=A dedicated LuCI JS package for the Xunison Exigo Hub D50 5G.
LUCI_DEPENDS:=+sms-tool +quectel-cm +kmod-pcie_mhi 
LUCI_PKGARCH:=all
PKG_LICENSE:=GNU
PKG_VERSION:=1.5
PKG_RELEASE:=20260429

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


